"use client"

import React, { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { Slider } from "@/components/ui/slider"
import { Maximize2, Minimize2, ZoomIn, ZoomOut, RefreshCw } from "lucide-react"
import type { VirtualTour } from "@/lib/types"

interface AdvancedPanoramaViewerProps {
  tour: VirtualTour
  sessionId?: string
  onSave?: (tour: VirtualTour) => void
}

/**
 * 🌀 AdvancedPanoramaViewer
 * Displays the stitched panorama generated by FastAPI backend.
 * Uses Pannellum for immersive 360° view.
 */
export function AdvancedPanoramaViewer({ tour }: AdvancedPanoramaViewerProps) {
  const viewerRef = useRef<HTMLDivElement>(null)
  const pannellumRef = useRef<any>(null)
  const containerRef = useRef<HTMLDivElement>(null)

  const [zoom, setZoom] = useState(100)
  const [pitch, setPitch] = useState(0)
  const [yaw, setYaw] = useState(0)
  const [isFullscreen, setIsFullscreen] = useState(false)

  const backendUrl = "http://localhost:8000"
  const stitchedUrl = `${backendUrl}/panoramas/${tour.id}_panorama.jpg`

  useEffect(() => {
    const initViewer = async () => {
      if (!viewerRef.current) return

      // ✅ Step 1: Check if panorama exists
      const panoramaExists = await fetch(stitchedUrl, { method: "HEAD" })
        .then((res) => res.ok)
        .catch(() => false)

      // ✅ Step 2: Trigger stitching only if needed
      if (!panoramaExists) {
        try {
          const res = await fetch(`${backendUrl}/stitch-panorama/${tour.id}`, { method: "POST" })
          if (res.ok) {
            console.log("✅ Stitching triggered for:", tour.id)
          } else {
            console.warn("⚠️ Stitch request failed:", await res.text())
          }
        } catch (err) {
          console.error("❌ Failed to trigger stitching:", err)
        }
      } else {
        console.log("🖼️ Panorama already exists, skipping stitching.")
      }

      // ✅ Step 3: Ensure Pannellum is loaded
      if (!window.pannellum) {
        await new Promise<void>((resolve) => {
          const script = document.createElement("script")
          script.src = "https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js"
          script.async = true
          script.onload = () => resolve()
          document.head.appendChild(script)

          const link = document.createElement("link")
          link.rel = "stylesheet"
          link.href = "https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.css"
          document.head.appendChild(link)
        })
      }

      // Destroy old viewer if it exists
      if (pannellumRef.current) pannellumRef.current.destroy()

      // ✅ Step 4: Initialize Pannellum viewer
      pannellumRef.current = window.pannellum.viewer(viewerRef.current, {
        type: "equirectangular",
        panorama: stitchedUrl,
        autoLoad: true,
        showControls: false,
        hfov: zoom,
        minHfov: 30,
        maxHfov: 120,
        pitch,
        yaw,
      })

      pannellumRef.current.on("mouseup", () => {
        setPitch(pannellumRef.current.getPitch())
        setYaw(pannellumRef.current.getYaw())
      })
    }

    initViewer()

    return () => pannellumRef.current?.destroy()
  }, [tour.id]) // ✅ depend only on tour.id

  // Zoom
  useEffect(() => {
    if (pannellumRef.current) pannellumRef.current.setHfov(zoom)
  }, [zoom])

  // Fullscreen
  const toggleFullscreen = () => {
    if (!containerRef.current) return
    if (document.fullscreenElement) document.exitFullscreen()
    else containerRef.current.requestFullscreen()
  }

  useEffect(() => {
    const handleFullscreenChange = () => setIsFullscreen(!!document.fullscreenElement)
    document.addEventListener("fullscreenchange", handleFullscreenChange)
    return () => document.removeEventListener("fullscreenchange", handleFullscreenChange)
  }, [])

  // Reset
  const resetView = () => {
    if (!pannellumRef.current) return
    pannellumRef.current.setPitch(0)
    pannellumRef.current.setYaw(0)
    pannellumRef.current.setHfov(100)
    setPitch(0)
    setYaw(0)
    setZoom(100)
  }

  return (
    <div ref={containerRef} className="relative h-screen w-full bg-black">
      {/* 🖼️ Viewer */}
      <div ref={viewerRef} className="absolute inset-0" />

      {/* 🎛️ Controls */}
      <div className="absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center gap-3 rounded-2xl bg-black/40 px-4 py-2 text-white backdrop-blur-md">
        <Button variant="ghost" size="icon" onClick={() => setZoom((z) => Math.min(z + 10, 120))} title="Zoom In">
          <ZoomIn className="h-5 w-5" />
        </Button>

        <div className="w-40">
          <Slider value={[zoom]} min={30} max={120} step={1} onValueChange={(val) => setZoom(val[0])} />
        </div>

        <Button variant="ghost" size="icon" onClick={() => setZoom((z) => Math.max(z - 10, 30))} title="Zoom Out">
          <ZoomOut className="h-5 w-5" />
        </Button>

        <Button variant="ghost" size="icon" onClick={resetView} title="Reset View">
          <RefreshCw className="h-5 w-5" />
        </Button>

        <Button variant="ghost" size="icon" onClick={toggleFullscreen} title="Toggle Fullscreen">
          {isFullscreen ? <Minimize2 className="h-5 w-5" /> : <Maximize2 className="h-5 w-5" />}
        </Button>
      </div>
    </div>
  )
}

// global pannellum type
declare global {
  interface Window {
    pannellum: any
  }
}
